//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaidShirts.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int idOrder { get; set; }
        public Nullable<int> idBasket { get; set; }
        public Nullable<double> sum { get; set; }
    
        public virtual Basket Basket { get; set; }
    }
}
